{{ if .Values.speedtest.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: '{{ .Values.speedtest.name }}'
  name: '{{ .Values.speedtest.name }}'
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    matchLabels:
      app: '{{ .Values.speedtest.name }}'
  replicas: 1
  template:
    metadata:
      labels:
        app: '{{ .Values.speedtest.name }}'
    spec:
      containers:
      - name: '{{ .Values.speedtest.name }}'
        {{- with .Values.speedtest.image }}
        image: "{{- if .registry -}}{{ .registry }}/{{ .image }}{{ else }}{{ .image }}{{- end -}}:{{ .tag }}{{- if (.digest) -}} @{{.digest}} {{- end -}}"
        {{- end }}
        imagePullPolicy: {{ .Values.speedtest.image.pullPolicy }}
        ports:
          {{- range $key, $value := .Values.speedtest.containerPort }}
          - name: {{ $key }}
            containerPort: {{ $value }}
            protocol: TCP
          {{- end }}
      {{- if .Values.speedtest.image.secret }}
      imagePullSecrets:
      - name: '{{ .Values.speedtest.image.secret }}'
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.speedtest.name }}'
  namespace: '{{ .Release.Namespace }}'
spec:
  type: NodePort
  ports:
  - port: {{ .Values.speedtest.containerPort.http }}
    protocol: TCP
    targetPort: {{ .Values.speedtest.containerPort.http }}
    nodePort: {{ .Values.speedtest.targetPort.http }}
  selector:
    app: '{{ .Values.speedtest.name }}'
{{ end -}}
