{{ if .Values.tm.create -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: '{{ .Values.tm.name }}'
  name: '{{ .Values.tm.name }}'
  namespace: '{{ .Release.Namespace }}'
spec:
  selector:
    matchLabels:
      app: '{{ .Values.tm.name }}'
  serviceName: '{{ .Values.tm.name }}'
  replicas: 1
  template:
    metadata:
      labels:
        app: '{{ .Values.tm.name }}'
    spec:
      terminationGracePeriodSeconds: {{ .Values.tm.terminationGracePeriodSeconds }}
      initContainers:
      - name: 'test-init'
        image: busybox:stable
        command:
          - "/bin/sh"
        args:
          - "-c"
          - "touch /usr/src/app/db/test && exit 0 || exit 1"
        volumeMounts:
        - mountPath: /usr/src/app/db
          name: '{{ .Values.pvc.name }}'
          subPath: '{{ .Values.tm.path.db }}'
      containers:
      - name: '{{ .Values.tm.name }}'
        {{- with .Values.tm.image }}
        image: "{{- if .registry -}}{{ .registry }}/{{ .image }}{{ else }}{{ .image }}{{- end -}}:{{ .tag }}{{- if (.digest) -}} @{{.digest}} {{- end -}}"
        {{- end }}
        imagePullPolicy: {{ .Values.tm.image.pullPolicy }}
        ports:
          {{- range $key, $value := .Values.tm.containerPort }}
          - name: {{ $key }}
            containerPort: {{ $value }}
            protocol: TCP
          {{- end }}
        volumeMounts:
        - mountPath: /usr/src/app/db
          name: '{{ .Values.pvc.name }}'
          subPath: '{{ .Values.tm.path.db }}'
      volumes:
      - name: '{{ .Values.pvc.name }}'
        persistentVolumeClaim:
          claimName: '{{ .Values.pvc.name }}'
      {{- if .Values.tm.image.secret }}
      imagePullSecrets:
      - name: '{{ .Values.tm.image.secret }}'
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.tm.name }}'
  namespace: '{{ .Release.Namespace }}'
spec:
  type: NodePort
  ports:
  - port: {{ .Values.tm.containerPort.http }}
    protocol: TCP
    targetPort: {{ .Values.tm.containerPort.http }}
    nodePort: {{ .Values.tm.targetPort.http }}
  selector:
    app: '{{ .Values.tm.name }}'
{{ end -}}
